openapi: 3.0.1
info:
  title: Ideapack API
  description: 'This is an API of Ideapack connector.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /tasks:
    get:
      tags:
        - task
      summary: Returns the task list
      description: Returns the task list
      operationId: getTasks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskList'
  /task/{taskId}:
    get:
      tags:
        - task
      summary: Find task by Id
      operationId: getTaskById
      parameters:
        - name: taskId
          in: path
          description: Id of task that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Task'
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: Invalid Id supplied
          content: {}
        404:
          description: Task not found
          content: {}
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        taskId:
          type: integer
          format: int64
        description:
          type: string
      xml:
        name: Task
    TaskList:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Task'
